### ISSUE TITLE
HLAassoc > Omnibus Test

### ISSUE THREAD

**Issue by DelnazRoshandel** [immunogenomics/HLA-TAPAS#18]
I want to try omnibus test and I am wondering how the .bim file of reference panel should look like, should all the AA that are on the same position have the same coordinate? I did HLA imputation on Michigan server and there is a one base per difference between AAs that are on the same position:

6 AA-A--2-29910398-exon1-R 0 29910398 T A
6 AA-A--2-29910398-exon1-W 0 29910399 A T
6 AA-A--2-29910398-exon1-x 0 29910400 T A

And often the coordinate doesn't match the one that in is the ID:

6 AA-A--22-29910338-exon1-V 0 29910385 A T

**Comment by DelnazRoshandel** [comment]
Ok I find the link for the. bim files here:
https://github.com/immunogenomics/HLA-TAPAS/issues/15

Which is similar to what I had. So I am assuming somehow it works.

Now I have other problems with omnibus test. First of all it doesn't recognize the "OMNIBUS_LINEAR" and says "invalid choice: 'OMNIBUS_LINEAR' (choose from 'LOGISTIC', 'LINEAR', 'OMNIBUS')"

And when I choose "OMNIBUS", I get another error:

Traceback (most recent call last):
  File "/python/3.8.0/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/python/3.8.0/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/HLA-TAPAS/HLAassoc/__main__.py", line 227, in <module>
    HLAassoc(args.Main_Menu, args.out, args.dependency,
  File "/HLA-TAPAS/HLAassoc/HLAassoc.py", line 446, in __init__
    if exists(which("Rscript")):
  File "/python/3.8.0/lib/python3.8/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

**Comment by steletvinicius** [comment]
Got the same error solved installing R on your virtual environment running HLA-TAPAS.
